### ISSUE TITLE
Lot of Starting Apache httpd web server: apache2 in the log.

### ISSUE THREAD

**Issue by rjm12rjm12** [BeardedTek/HassPyFrigate#1]
This looks great, just installed it.  Will try out when I get home.
Should this be happening continuously?

[15:46:48] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:49] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:49] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:50] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:50] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:51] INFO: Starting Apache...
Starting Apache httpd web server: apache2.
[15:46:51] INFO: Starting Apache...
Starting Apache httpd web server: apache2.

**Comment by williamkennyAK** [comment]
I've noticed this as well.  It runs perfectly fine, but definitely filling the error log.
A new version is coming out VERY soon that adds an event viewer and some visual improvements.  Should be out within a few days.

**Comment by rjm12rjm12** [comment]
Great, I'll be looking for the update.  Any thoughts about a way to only get one notification per some time period.
I'm tracking when my dog is ready to come in, but just want to get one notification.

Thanks for you work.

Rob

________________________________

**Comment by BeardedTek** [comment]
https://community.home-assistant.io/t/frigate-mobile-app-notifications/311091 contains a blueprint that does this.  I have not implemented it yet as I'm trying to get more notifications for testing at this point, but will most likely write one for the next iteration of the addon.

**Comment by bruno-dogancic** [comment]
I would like to try this one out but I cannot set it up...
I have installed and started addon, in home assistant configuration I did this: (Only changed my hass public ip)

```
rest_command:
  hasspyfrigate:
    url: https://mypublicip.duckdns.org:8123/cgi-bin/hasspyrest.py
    method: POST
    headers:
      accept: "application/json, text/html"
      user-agent: "Mozilla/5.0 {{ useragent }}"
    payload: '{
      "table": "events",
      "debug": "1",
      "function": "INSERT",
      "columns" : {
      "event_id": "{{event_id}}",
      "url": "{{url}}",
      "camera": "{{camera}}",
      "type": "{{type}}",
      "bbox": "{{bbox}}"
      }
      }'
    content_type: "application/json; charset=utf-8"
```

And added notification automation as this (also, only changed my hass ip address)

```
- id: "hasspyfrigate"
  alias: HassPyFrigate
  description: Object Detection Alerts Using HassPyFrigate
  trigger:
    - platform: mqtt
      topic: frigate/events
  condition:
    - condition: template
      value_template: '{{ trigger.payload_json["type"] == "end" }}'
    - condition: template
      value_template:
        "{{ trigger.payload_json[\"after\"][\"label\"] == \"person\" or\n\
        \   trigger.payload_json[\"after\"][\"label\"] == \"bird\" or\n   trigger.payload_json[\"\
        after\"][\"label\"] == \"dog\" or\n   trigger.payload_json[\"after\"][\"label\"\
        ] == \"cat\" or\n   trigger.payload_json[\"after\"][\"label\"] == \"bear\" or\n\
        \   trigger.payload_json[\"after\"][\"label\"] == \"horse\" \n}}"
  action:
    - service: notify.notify
      data:
        message: '{{ trigger.payload_json["after"]["label"] | title }} Detected'
        data:
          notification_icon: mdi:cctv
          ttl: 0
          priority: high
          sticky: true
          actions:
            - action: URI
              title: Event Viewer
              uri: https://mypublicip.duckdns.org:8123/cgi-bin/hasspyfrigate.py?id={{trigger.payload_json['after']['id']}}&camera={{trigger.payload_json['after']['camera']}}&bbox=true
          image: /api/frigate/notifications/{{trigger.payload_json['after']['id']}}/snapshot.jpg?bbox=1
          tag: '{{trigger.payload_json["after"]["id"]}}'
          alert_once: true
    - service: rest_command.hasspyfrigate
      data:
        event_id: "{{trigger.payload_json['after']['id']}}"
        camera: "{{trigger.payload_json['after']['camera']}}"
        type: "{{ trigger.payload_json['after']['label'] | title }}"
        bbox: 1
  mode: single
```
Do I have to do anything besides that? I run my homeassistant on raspberry PI as Home Assistant Operating System.

Cheers!

**Comment by BeardedTek** [comment]
```
actions:
            - action: URI
              title: Event Viewer
              uri: https://mypublicip.duckdns.org:8123/cgi-bin/hasspyfrigate.py?id={{trigger.payload_json['after']['id']}}&camera={{trigger.payload_json['after']['camera']}}&bbox=true
```
Should be:

```
actions:
            - action: URI
              title: Event Viewer
              uri: https://mypublicip.duckdns.org:8001/cgi-bin/hasspyfrigate.py?id={{trigger.payload_json['after']['id']}}&camera={{trigger.payload_json['after']['camera']}}&bbox=true
```

 port 8001 as this is where the port should be configured by default.

The addon runs an instance of apache in docker which home assistant routes to the port forwarded in the config below.

![Screenshot_20211218-100635_Home Assistant.png](https://user-images.githubusercontent.com/93575915/146652990-6fd8c1bd-61d2-4f38-81ab-5f778930632d.png)

**Comment by BeardedTek** [comment]
The code here is in a state of flux.  The README is for v0.2, but the addon is still running v0.1.  Please refer to the readme in the v0.1 release as it has changed slightly:




# HassPyFrigate
## Python 3 CGI script for better looking notifications
![v0.1](img/HassPyFrigate.png)

# SERVER SIDE SETUP
 * This will run on a standard installation of Apache2.  Place /html/cgi-bin/hasspyfrigate.py in your cgi-bin location 
#### (/usr/lib/cgi-bin is the default on Ubuntu)
* Place /html/css/hasspyfrigate.css into any web accessible folder (<html_root>/css preferred)

# Home Assistant Automations

## Android Companion App Notification
#### Example Android Actionable Notification
Click on "Event Viewer" to view HassPyFrigate Event Viewer
![Android Actionable Notification](img/AndroidNotification.png)
The following Automation will send an actionable notification to the android companion app (Should work with iOS as well)
```
alias: HassPyFrigate Alert
description: HassPyFrigate Object Detection Alerts Using Frigate
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: '{{ trigger.payload_json["type"] == "end" }}'
  - condition: template
    value_template: |-
      {{ trigger.payload_json["after"]["label"] == "person" or 
         trigger.payload_json["after"]["label"] == "car" or
         trigger.payload_json["after"]["label"] == "bird" or
         trigger.payload_json["after"]["label"] == "dog" or
         trigger.payload_json["after"]["label"] == "cat" or
         trigger.payload_json["after"]["label"] == "bear" or
         trigger.payload_json["after"]["label"] == "horse" 
      }}
action:
  - service: notify.mobile_app_sm_g986u1
    data:
      message: '{{ trigger.payload_json["after"]["label"] | title }} Detected'
      data:
        notification_icon: mdi:cctv
        ttl: 0
        priority: high
        sticky: true
        actions:
          - action: URI
            title: Snapshot
            uri: >-
              http://YOUR_SERVER/cgi-bin/hasspyfrigate.py?id={{trigger.payload_json['after']['id']}}&camera={{trigger.payload_json['after']['camera']}}&bbox=true&url=https://hass.jeandr.net/api/frigate/notifications/&time={{trigger.payload_json['after']['start_time']}}&css=../css/hasspyfrigate.css#
        image: >-
          /api/frigate/notifications/{{trigger.payload_json['after']['id']}}/snapshot.jpg?bbox=1
        tag: '{{trigger.payload_json["after"]["id"]}}'
        alert_once: true
mode: single

```
